# Hybrid Approach

from bson import ObjectId
from typing import List, Optional, Dict

class StudyGroup:
    def __init__(self, _id: Optional[ObjectId] = None, guild_id: int, name: str, category_id: int, creator_id: int, 
                 max_members: int = 10, member_ids: Optional[List[int]] = None, 
                 group_role_id: Optional[int] = None, text_id: Optional[int] = None, 
                 vc_id: Optional[int] = None, info_embed_id: Optional[int] = None, 
                 start_time: Optional[datetime] = None, duration: int = 43200,  # 12 hours in seconds
                 speak_enabled: bool = True, video_mode: str = "off", 
                 video_timer: int = 10, active: bool = True,
                 checkin_sessions: Optional[List[Dict]] = None):
        self._id = _id or ObjectId()
        self.guild_id = guild_id
        self.name = name
        self.group_id = str(uuid4())  # Generate a unique ID
        self.creator_id = creator_id
        self.owner_id = creator_id  # Initially, the creator is the owner
        self.category_id = category_id
        self.max_members = max_members
        self.member_ids = member_ids or [creator_id]  # Creator is always a member
        self.group_role_id = group_role_id
        self.text_id = text_id
        self.vc_id = vc_id
        self.info_embed_id = info_embed_id
        self.start_time = start_time or datetime.utcnow()
        self.duration = duration
        self.end_time = self.start_time + timedelta(seconds=duration)
        self.speak_enabled = speak_enabled
        self.video_mode = video_mode
        self.video_timer = video_timer
        self.active = active
        self.checkin_sessions = checkin_sessions or []

class CheckinSession:
    def __init__(self, _id: Optional[ObjectId] = None, guild_id: int, name: str, creator_id: int, text_id: int,
                 member_ids: Optional[List[int]] = None, duration: int = 3600,  # 1 hour in seconds
                 start_time: Optional[datetime] = None, last_reminder_time: Optional[datetime] = None,
                 next_reminder_time: Optional[datetime] = None, reminder_count: int = 0,
                 last_reminder_message_id: Optional[int] = None, active: bool = True,
                 study_group_id: Optional[ObjectId] = None):
        self._id = _id or ObjectId()
        self.guild_id = guild_id
        self.name = name
        self.creator_id = creator_id
        self.owner_id = creator_id  # Initially, the creator is the owner
        self.text_id = text_id
        self.member_ids = member_ids or [creator_id]  # Creator is always a member
        self.duration = duration
        self.start_time = start_time or datetime.utcnow()
        self.last_reminder_time = last_reminder_time or datetime.utcnow()
        self.next_reminder_time = next_reminder_time or self.start_time + timedelta(seconds=duration)
        self.reminder_count = reminder_count
        self.last_reminder_message_id = last_reminder_message_id
        self.active = active
        self.study_group_id = study_group_id

class Task:
    def __init__(self, _id: Optional[ObjectId] = None, user_id: int, description: str, completed: bool = False, 
                 created_at: Optional[datetime] = None):
        self._id = _id or ObjectId()
        self.user_id = user_id
        self.description = description
        self.completed = completed
        self.created_at = created_at or datetime.utcnow()

class UserPermissions:
    def __init__(self, _id: Optional[ObjectId] = None, user_id: int, guild_id: int, permissions: List[str]):
        self._id = _id or ObjectId()
        self.user_id = user_id
        self.guild_id = guild_id
        self.permissions = permissions

class GuildSettings:
    def __init__(self, _id: Optional[ObjectId] = None, guild_id: int, vc_cleanup_time: int = 600, 
                 vc_category_id: Optional[int] = None):
        self._id = _id or ObjectId()
        self.guild_id = guild_id
        self.vc_cleanup_time = vc_cleanup_time
        self.vc_category_id = vc_category_id

# Key Points:

# _id: Each data model now includes an _id attribute, which will be automatically generated by MongoDB as the primary key for each document.
# study_group_id: The CheckinSession model now has a study_group_id field that references the _id of a StudyGroup document. This is an example of using references to link related data.
# checkin_sessions: The StudyGroup model now includes a checkin_sessions field, which is a list of dictionaries. This is an example of embedding documents within a parent document.

# Remember:

# You can adjust the data models and relationships based on your specific needs and how you want to structure your data.
# You can also use MongoDB's aggregation framework to perform more complex queries and data analysis.

---
# Original Implementation

# from typing import List, Optional, Dict
# from uuid import uuid4
# from bson import ObjectId
# 
# class User:
#     def __init__(self, _id: Optional[ObjectId] = None, user_id: int, 
#                  guild_id: int, preferences: Optional[Dict] = None, 
#                  settings: Optional[Dict] = None, statistics: Optional[Dict] = None):
#         self._id = _id or ObjectId()
#         self.user_id = user_id
#         self.guild_id = guild_id
#         self.preferences = preferences or {}
#         self.settings = settings or {}
#         self.statistics = statistics or {}
# 
#  class StudyGroup:
#     def __init__(self, guild_id: int, name: str, category_id: int, creator_id: int, 
#                  max_members: int = 10, member_ids: Optional[List[int]] = None, 
#                  group_role_id: Optional[int] = None, text_id: Optional[int] = None, 
#                  vc_id: Optional[int] = None, info_embed_id: Optional[int] = None, 
#                  start_time: Optional[datetime] = None, duration: int = 43200,  # 12 hours in seconds
#                  speak_enabled: bool = True, video_mode: str = "off", 
#                  video_timer: int = 10, active: bool = True):
#         self.guild_id = guild_id
#         self.name = name
#         self.group_id = str(uuid4())  # Generate a unique ID
#         self.creator_id = creator_id
#         self.owner_id = creator_id  # Initially, the creator is the owner
#         self.category_id = category_id
#         self.max_members = max_members
#         self.member_ids = member_ids or [creator_id]  # Creator is always a member
#         self.group_role_id = group_role_id
#         self.text_id = text_id
#         self.vc_id = vc_id
#         self.info_embed_id = info_embed_id
#         self.start_time = start_time or datetime.utcnow()
#         self.duration = duration
#         self.end_time = self.start_time + timedelta(seconds=duration)
#         self.speak_enabled = speak_enabled
#         self.video_mode = video_mode
#         self.video_timer = video_timer
#         self.active = active
# 
# class CheckinSession:
#     def __init__(self, guild_id: int, name: str, creator_id: int, text_id: int,
#                  member_ids: Optional[List[int]] = None, duration: int = 3600,  # 1 hour in seconds
#                  start_time: Optional[datetime] = None, last_reminder_time: Optional[datetime] = None,
#                  next_reminder_time: Optional[datetime] = None, reminder_count: int = 0,
#                  last_reminder_message_id: Optional[int] = None, active: bool = True,
#                  study_group_id: Optional[str] = None):
#         self.session_id = str(uuid4())  # Generate a unique ID
#         self.guild_id = guild_id
#         self.name = name
#         self.creator_id = creator_id
#         self.owner_id = creator_id  # Initially, the creator is the owner
#         self.text_id = text_id
#         self.member_ids = member_ids or [creator_id]  # Creator is always a member
#         self.duration = duration
#         self.start_time = start_time or datetime.utcnow()
#         self.last_reminder_time = last_reminder_time or datetime.utcnow()
#         self.next_reminder_time = next_reminder_time or self.start_time + timedelta(seconds=duration)
#         self.reminder_count = reminder_count
#         self.last_reminder_message_id = last_reminder_message_id
#         self.active = active
#         self.study_group_id = study_group_id
# 
# class Task:
#     def __init__(self, user_id: int, description: str, completed: bool = False, 
#                  created_at: Optional[datetime] = None):
#        self.user_id = user_id
#        self.description = description
#        self.completed = completed
#        self.created_at = created_at or datetime.utcnow()
#
# class UserPermissions:
#     def __init__(self, user_id: int, guild_id: int, permissions: List[str]):
#        self.user_id = user_id
#        self.guild_id = guild_id
#        self.permissions = permissions
#
# class GuildSettings:
#     def __init__(self, guild_id: int, vc_cleanup_time: int = 600, 
#                 vc_category_id: Optional[int] = None):
#        self.guild_id = guild_id
#        self.vc_cleanup_time = vc_cleanup_time
#        self.vc_category_id = vc_category_id

###
